[package]
authors = ["Vitaly Domnikov <oss@vitaly.codes>"]
categories = ["embedded", "hardware-support", "no-std"]
description = "Peripheral access API for STM32G0 series microcontrollers"
documentation = "https://docs.rs/stm32g0xx-hal"
edition = "2018"
keywords = ["arm", "cortex-m", "stm32g0xx", "hal"]
license = "MIT/Apache-2.0"
name = "stm32g0xx-hal"
readme = "README.md"
repository = "https://github.com/stm32-rs/stm32g0xx-hal"
version = "0.1.0"

[package.metadata.docs.rs]
features = ["stm32g081", "rt"]
default-target = "thumbv6m-none-eabi"

[dependencies]
cortex-m = "0.7.1"
nb = "1.0.0"

# TODO(AJM): Remove once I figure out how to steal
# the correct parts of futures
[dependencies.cassette]
version = "0.2.1"
git = "https://github.com/jamesmunns/cassette"
branch = "main"

[dependencies.stm32g0]
version = "0.13.0"
features = ["rt"]

[dependencies.bare-metal]
version = "1.0.0"

[dependencies.embedded-hal]
features = ["unproven"]
version = "0.2.4"

[dependencies.void]
default-features = false
version = "1.0.2"

[dev-dependencies]
cortex-m-rt = "0.6.10"
cortex-m-rtic = "0.5.5"
cortex-m-semihosting = "0.3.5"
panic-halt = "0.2.0"
panic-semihosting = "0.5.3"
embedded-sdmmc = "0.2.1"
st7735-lcd = "0.6.1"
embedded-graphics = "0.5"
smart-leds = {git = "https://github.com/smart-leds-rs/smart-leds"}
ws2812-spi = {git = "https://github.com/smart-leds-rs/ws2812-spi-rs"}

[features]
rt = ["stm32g0/rt"]
stm32g030 = ["stm32g0/stm32g030", "stm32g0x0"]
stm32g070 = ["stm32g0/stm32g070", "stm32g0x0"]
stm32g031 = ["stm32g0/stm32g031", "stm32g0x1"]
stm32g041 = ["stm32g0/stm32g041", "stm32g0x1"]
stm32g071 = ["stm32g0/stm32g071", "stm32g0x1"]
stm32g081 = ["stm32g0/stm32g081", "stm32g0x1"]

stm32g0x0 = []
stm32g0x1 = []

[profile.dev]
incremental = false

[profile.release]
debug = false
codegen-units = 1
incremental = false
lto = true
